services:
  - type: web
    name: carryme
    plan: free
    runtime: docker
    autoDeploy: true


    buildCommand: dotnet publish -c Release -o out
    startCommand: ASPNETCORE_URLS=http://0.0.0.0:$PORT dotnet out/carryMe.dll
