services:
  - type: web
    name: carry-Me
    env: docker
    plan: free

    buildCommand: |
      dotnet publish -c Release -o out

    startCommand: |
      set -e
      echo "== Install rclone =="
      apt-get update && apt-get install -y rclone

      echo "== Write rclone.conf =="
      cat > rclone.conf <<'EOF'
      [supabase]
      type = s3
      provider = Other
      env_auth = false
      access_key_id = ${SB_S3_KEY}
      secret_access_key = ${SB_S3_SECRET}
      endpoint = https://${SB_PROJECT_REF}.supabase.co/storage/v1/s3
      no_check_bucket = true
      EOF

      mkdir -p wwwroot/uploads

      echo "== Ensure bucket structure on remote =="
      rclone mkdir supabase:${SB_BUCKET} --config rclone.conf || true
      rclone mkdir supabase:${SB_BUCKET}/uploads --config rclone.conf || true

      echo "== Restore DB & uploads (if exist) =="
      rclone ls supabase:${SB_BUCKET} --config rclone.conf || true
      rclone copy -v supabase:${SB_BUCKET}/carryme.db ./ --config rclone.conf || true
      rclone copy -v supabase:${SB_BUCKET}/uploads ./wwwroot/uploads --config rclone.conf || true
      ls -l || true
      [ -f carryme.db ] && echo "DB restored OK" || echo "DB not found on remote (first run?)"

      echo "== Start app =="
      set +e
      dotnet out/carryMe.dll &
      APP_PID=$!
      set -e

      echo "== Immediate backup once (seed remote) =="
      [ -f carryme.db ] && rclone copy -v ./carryme.db supabase:${SB_BUCKET} --config rclone.conf || true
      rclone copy -v ./wwwroot/uploads supabase:${SB_BUCKET}/uploads --config rclone.conf || true

      echo "== Fast backup loop (every 10s) =="
      while sleep 10; do
        [ -f carryme.db ] && rclone copy -v ./carryme.db supabase:${SB_BUCKET} --config rclone.conf || true
        rclone copy -v ./wwwroot/uploads supabase:${SB_BUCKET}/uploads --config rclone.conf || true
      done
